### ISSUE TITLE
Bindings are always set to WASD, even when movement keys are bound differently.

### ISSUE THREAD

**Issue by Jazztache** [kestalkayden/enhanced-movement-mod#3]
### Issue

Binds for directional dashes do not update when you change your movement keys. For example, using ESDF in order to put your movement keys ergonomically closer to the home row, and free up A and Q for mod bindings.

In this scheme, S is walk left, and dash backwards. W, which is my new drop key, is dash forward.

However, someone else probably has another unique binding, so it would be a better idea if the key used was the one defined in the controls section of the vanilla Minecraft menu. 

### Solution

On file `https://github.com/kestalkayden/enhanced-movement-mod/blob/main/src/main/java/net/fabricmc/EnhancedMovement/EnhancedMovement.java` at lines 118 - 121

The code seems to only be referencing the default key binding, instead of the binding that the user has specified.

`forwardKey.getDefaultKey().getCode()` shouldn't be referencing getDefaultKey(). If the library being used contains something like a `getUserDefinedKey()` or just `getKey()` that might solve the issue.

Thankyou!

**Comment by kestalkayden** [comment]
Sincere apologies for the delay on this. This has been fixed with 1.0.5.
